#!/usr/bin/env python3
"""Trace the selected two-colour case artwork into nozzle-safe SVG layers."""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "EurasianSynergyFlute_logo_2color.png"
OUTPUT_DIR = ROOT / "generated"


def write_if_changed(output: Path, content: str) -> None:
    if output.exists() and output.read_text(encoding="utf-8") == content:
        return
    output.write_text(content, encoding="utf-8")


def artwork_masks(source: Path) -> tuple[np.ndarray, np.ndarray]:
    image = np.asarray(Image.open(source).convert("L"))
    ink = np.where(image < 128, 255, 0).astype(np.uint8)
    occupied_rows = np.flatnonzero(np.any(ink, axis=1))
    if occupied_rows.size == 0:
        raise ValueError(f"{source}: no dark artwork found")

    gaps = np.diff(occupied_rows)
    split_index = int(np.argmax(gaps))
    if gaps[split_index] < 8:
        raise ValueError(f"{source}: could not separate title and map")
    split_y = int((occupied_rows[split_index] + occupied_rows[split_index + 1]) // 2)

    title = ink.copy()
    title[split_y + 1 :] = 0
    landmass = ink.copy()
    landmass[: split_y + 1] = 0
    return title, landmass


def nozzle_safe(mask: np.ndarray, target_width_mm: float, nozzle_mm: float) -> np.ndarray:
    xs = np.flatnonzero(np.any(mask, axis=0))
    pixel_mm = target_width_mm / (int(xs[-1]) - int(xs[0]) + 1)
    diameter = max(1, int(round(nozzle_mm / pixel_mm)))
    if diameter % 2 == 0:
        diameter += 1
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (diameter, diameter))
    closed = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    return cv2.morphologyEx(closed, cv2.MORPH_OPEN, kernel)


def svg_for(mask: np.ndarray, output: Path, *, check: bool = False) -> tuple[int, int]:
    ys, xs = np.nonzero(mask)
    x0, x1 = int(xs.min()), int(xs.max())
    y0, y1 = int(ys.min()), int(ys.max())
    cropped = mask[y0 : y1 + 1, x0 : x1 + 1]
    height, width = cropped.shape
    contours, _ = cv2.findContours(
        cropped,
        cv2.RETR_LIST,
        cv2.CHAIN_APPROX_TC89_KCOS,
    )
    commands: list[str] = []
    for contour in contours:
        epsilon = max(0.35, cv2.arcLength(contour, True) * 0.00035)
        points = cv2.approxPolyDP(contour, epsilon, True).reshape(-1, 2)
        if len(points) < 3 or abs(cv2.contourArea(points)) < 1.0:
            continue
        coordinates = [(float(x), float(height - y)) for x, y in points]
        command = "M " + " L ".join(f"{x:.3f},{y:.3f}" for x, y in coordinates) + " Z"
        commands.append(command)
    if not commands:
        raise ValueError(f"{output}: vectorization produced no paths")
    document = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}">\n'
        f'  <path d="{" ".join(commands)}" fill="#000" fill-rule="evenodd"/>\n'
        "</svg>\n"
    )
    if check:
        if not output.exists() or output.read_text(encoding="utf-8") != document:
            raise SystemExit(f"{output.relative_to(ROOT)} is stale; regenerate case logo vectors")
    else:
        write_if_changed(output, document)
    return width, height


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nozzle", type=float, default=0.4, help="nozzle diameter in mm")
    parser.add_argument("--check", action="store_true", help="verify generated SVGs")
    args = parser.parse_args()
    title, landmass = artwork_masks(SOURCE)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    title_size = svg_for(
        nozzle_safe(title, 190.0, args.nozzle),
        OUTPUT_DIR / "case_logo_title.svg",
        check=args.check,
    )
    map_size = svg_for(
        nozzle_safe(landmass, 84.0, args.nozzle),
        OUTPUT_DIR / "case_logo_map.svg",
        check=args.check,
    )
    dimensions = (
        "// Generated by tools/vectorize_case_logo.py; do not edit.\n"
        f"logo_title_source_size = [{title_size[0]}, {title_size[1]}];\n"
        f"logo_map_source_size = [{map_size[0]}, {map_size[1]}];\n"
    )
    dimensions_path = OUTPUT_DIR / "case_logo_dimensions.scad"
    if args.check:
        if not dimensions_path.exists() or dimensions_path.read_text(encoding="utf-8") != dimensions:
            raise SystemExit(
                f"{dimensions_path.relative_to(ROOT)} is stale; regenerate case logo vectors"
            )
    else:
        write_if_changed(dimensions_path, dimensions)


if __name__ == "__main__":
    main()
